window.SITE = {
  name: 'Phạm Bá Tuấn Khoa',
  short: 'Khoa',
  role: 'Full-stack software engineer',
  email: 'pbtkhoa@gmail.com',
  github: 'https://github.com/pbtkhoa',
  linkedin: 'https://linkedin.com/in/pbtkhoa',
  status: 'Open to remote roles and freelance projects',
  pitch: 'I build Shopware stores, Laravel and Symfony apps and Vue front ends for teams around the world, from the database to the deploy.',
  stats: [
    { value: '10', label: 'years shipping production code' },
    { value: '20+', label: 'online stores and apps delivered' },
    { value: '2017', label: 'freelancing alongside every job' },
    { value: '5', label: 'companies, plus freelance clients' },
  ],
  stack: ['PHP', 'Symfony', 'Laravel', 'Shopware 6', 'Vue 3', 'TypeScript', 'React', 'React Native', 'Drupal', 'Node.js', 'MySQL', 'PostgreSQL', 'Redis', 'Docker', 'AWS', 'Tailwind CSS', 'Playwright', 'Pest'],
  clients: ['van Laack', 'Vorwerk Thermomix', 'GLS Bank', 'Egret', 'Biomex', 'Cityschuh', 'manomama', 'Brichbag', 'Roto-store', 'Kraft'],
  services: [
    { key: 'shopware', title: 'Shopware 6 development', blurb: 'Plugins, apps and themes, complete store setups, version upgrades and integrations with payment, shipping and ERP systems.', points: ['Custom plugins and apps', 'Storefront themes in Twig and Vue', 'Upgrades to the latest Shopware 6', 'Payment, shipping and ERP integrations'] },
    { key: 'apps', title: 'Laravel and Symfony apps', blurb: 'Business web apps, SaaS products, admin tools and APIs. I also move older systems onto current PHP, Symfony and Laravel versions.', points: ['Multi-tenant SaaS', 'REST APIs and API Platform', 'Legacy upgrades without downtime', 'AWS, Vapor and Docker deploys'] },
    { key: 'frontend', title: 'Vue, React and mobile', blurb: 'Fast front ends in Vue 3 and React, and cross-platform mobile apps in React Native.', points: ['Vue 3 and Nuxt', 'React and Next.js', 'React Native apps', 'Tailwind CSS design systems'] },
    { key: 'team', title: 'Remote team member', blurb: 'Join your team for months, not days. I keep hours that overlap with yours, use your tools and ship through your review process.', points: ['Hours that overlap with yours', 'Jira, GitLab, GitHub, Slack', 'Code review and pairing', 'Long-term retainer or full-time'] },
  ],
  process: [
    { title: 'Talk', text: 'A short call or email thread about the goal, the users and the deadline.' },
    { title: 'Scope', text: 'A written plan with milestones and an estimate you can take to your team.' },
    { title: 'Build', text: 'Weekly demos on a staging site. You see progress every week, not just at the end.' },
    { title: 'Launch and support', text: 'Deploy, monitor, fix. Ongoing maintenance on a monthly plan if you want it.' },
  ],
  work: [
    { slug: 'shopware', title: 'Shopware 6 stores and plugins', org: 'Shape & Shift · freelance', years: '2021 – now', summary: 'Storefronts for fashion and B2B shops and the extensions behind them: Checkout.com payments, the Sprinque B2B-credit app, a blog plugin and a Node.js SDK for Shopware.', tags: ['Symfony', 'Vue', 'MySQL', 'Shopware 6'], tone: 'a' },
    { slug: 'accounting', title: 'Multi-tenant accounting SaaS', org: 'Shape & Shift', years: '2021 – 2023', summary: 'Double-entry ledger, invoicing, bank reconciliation, payroll and reporting. Python Lambdas, OpenAI and Twilio SMS on Laravel Vapor.', tags: ['Laravel', 'Vue 3', 'AWS', 'Stripe'], tone: 'b' },
    { slug: 'banking', title: 'GLS Bank sign-on and account opening', org: 'Solio', years: '2023 – now', summary: 'Single sign-on with OAuth2 and LDAP, and a business account-opening app with Postident identity checks.', tags: ['Symfony', 'OAuth2', 'LDAP'], tone: 'c' },
    { slug: 'thermomix', title: 'Lead management for Thermomix', org: 'Solio', years: '2023 – now', summary: 'A Drupal 11 tool for Vorwerk Austria: lead assignment, reminders, CSV import and SAP export.', tags: ['Drupal 11', 'PHP', 'SAP export'], tone: 'd' },
    { slug: 'crypto', title: 'Crypto trading platform', org: 'Rikkeisoft', years: '2017 – 2019', summary: 'A microservice trading system built by a team of 13. I was team lead and core developer.', tags: ['Laravel', 'Node.js', 'Socket.IO', 'Docker'], tone: 'e' },
    { slug: 'posbill', title: 'Posbill point of sale', org: 'NFQ', years: '2019 – 2021', summary: 'A point-of-sale app for hospitality, built in React Native.', tags: ['React Native', 'React'], tone: 'f' },
  ],
  experience: [
    { years: '2023 – now', role: 'Software Engineer', org: 'Solio', note: 'Drupal, Symfony and Shopware for Austrian and German clients.' },
    { years: '2021 – 2023', role: 'Software Engineer', org: 'Shape & Shift', note: 'Shopware 6 extensions and a Laravel accounting SaaS.' },
    { years: '2019 – 2021', role: 'Frontend Developer', org: 'NFQ', note: 'React and React Native apps for clients.' },
    { years: '2017 – 2019', role: 'Team Lead', org: 'Rikkeisoft', note: 'Led client projects, set up the Git workflow. Outstanding Employee 2018.' },
    { years: '2016 – 2017', role: 'Software Engineer', org: 'Junoteam', note: 'WordPress and Symfony sites, plugins and themes.' },
    { years: '2017 – now', role: 'Freelance engineer', org: 'Independent', note: 'Stores, plugins, web and mobile apps for clients worldwide.' },
  ],
  faq: [
    { q: 'Where are you based?', a: 'In Vietnam. I work remotely with clients around the world and keep regular hours that overlap with yours.' },
    { q: 'Do you work full-time or by project?', a: 'Both. I take full-time remote roles, fixed-scope projects and monthly retainers.' },
    { q: 'Which languages do you work in?', a: 'English for calls, tickets and documentation.' },
    { q: 'Can you sign an NDA?', a: 'Yes. Most of my client work is under NDA already.' },
  ],
};
